# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0017_auto_20170511_1900'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestigator',
            name='institution',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='investigator',
            name='institution',
            field=models.TextField(blank=True),
        ),
    ]
