# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-01-22 20:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_auto_20180122_2002'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalinvestigator',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='institution',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
