# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-03-14 17:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0018_historicalposition_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='role',
            field=models.CharField(choices=[(b'CM', b'Corporation Member'), (b'TR', b'Trustee'), (b'FEL', b'Friday Evening Lecturer')], default=b'CM', max_length=3),
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.CharField(choices=[(b'CM', b'Corporation Member'), (b'TR', b'Trustee'), (b'FEL', b'Friday Evening Lecturer')], default=b'CM', max_length=3),
        ),
    ]
