# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-05-09 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0019_auto_20180314_1707'),
    ]

    operations = [
        migrations.AlterField(
            model_name='affiliation',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.Institution'),
        ),
    ]
