# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-19 18:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0019_auto_20180122_2017'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='historicalinvestigator',
            name='institution',
        ),
        migrations.RemoveField(
            model_name='investigator',
            name='institution',
        ),
    ]
