# Generated by Django 2.2.4 on 2019-08-22 22:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0020_auto_20180509_1829'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalaffiliation',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalattendance',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcourse',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalcoursegroup',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinstitution',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalinvestigator',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalknowninstitution',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalknownlocation',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalknownperson',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallocalization',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicallocation',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalpartof',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalperson',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='historicalposition',
            name='history_change_reason',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='affiliation',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='attendance',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='course',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='coursegroup',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalaffiliation',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalattendance',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalcourse',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalcoursegroup',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\n    Use this field to specify a known institution (i.e. a location with an entry\n    in the Conceptpower name authority).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='browser.KnownInstitution'),
        ),
        migrations.AlterField(
            model_name='historicalinstitution',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalinvestigator',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalknowninstitution',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalknownlocation',
            name='external_uri',
            field=models.CharField(blank=True, help_text="Enter a resolvable URI from a geographic database, e.g. OpenStreetMap or GeoNames. If using OpenStreetMap, this can be the 'share URL'; be sure to select 'include marker.'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalknownlocation',
            name='geo_uri',
            field=models.CharField(blank=True, help_text="e.g. 'geo:39.96511,-75.19281?z=19'. For more information about Geo URIs, see https://en.wikipedia.org/wiki/Geo_URI_scheme", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='historicalknownlocation',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Decimal latitude, e.g. 48.1295', null=True),
        ),
        migrations.AlterField(
            model_name='historicalknownlocation',
            name='latitude_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('S', 'South')], help_text='\n    If the location is in the northern hemisphere, and has a positive latitude,\n    then the latitude cardinality is North.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalknownlocation',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal longitude, e.g. 128.7490', null=True),
        ),
        migrations.AlterField(
            model_name='historicalknownlocation',
            name='longitude_direction',
            field=models.CharField(blank=True, choices=[('E', 'East'), ('W', 'West')], help_text='\n    If the location is in the western hemisphere, and has a negative longitude,\n    then the longitude cardinality is East.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='historicalknownlocation',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalknownperson',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicallocalization',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\n    Use this field to specify a known location (i.e. a location with an entry\n    in the GeoNames database).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='browser.KnownLocation'),
        ),
        migrations.AlterField(
            model_name='historicallocation',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalpartof',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='authority',
            field=models.ForeignKey(blank=True, db_constraint=False, help_text='\n    Use this field to specify a known person (i.e. a person with an entry in\n    the Conceptpower name authority).', null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='browser.KnownPerson'),
        ),
        migrations.AlterField(
            model_name='historicalperson',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='role',
            field=models.CharField(choices=[('CM', 'Corporation Member'), ('TR', 'Trustee'), ('FEL', 'Friday Evening Lecturer')], default='CM', max_length=3),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='authority',
            field=models.ForeignKey(blank=True, help_text='\n    Use this field to specify a known institution (i.e. a location with an entry\n    in the Conceptpower name authority).', null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.KnownInstitution'),
        ),
        migrations.AlterField(
            model_name='institution',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='investigator',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='knowninstitution',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='knownlocation',
            name='external_uri',
            field=models.CharField(blank=True, help_text="Enter a resolvable URI from a geographic database, e.g. OpenStreetMap or GeoNames. If using OpenStreetMap, this can be the 'share URL'; be sure to select 'include marker.'", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='knownlocation',
            name='geo_uri',
            field=models.CharField(blank=True, help_text="e.g. 'geo:39.96511,-75.19281?z=19'. For more information about Geo URIs, see https://en.wikipedia.org/wiki/Geo_URI_scheme", max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='knownlocation',
            name='latitude',
            field=models.FloatField(blank=True, help_text='Decimal latitude, e.g. 48.1295', null=True),
        ),
        migrations.AlterField(
            model_name='knownlocation',
            name='latitude_direction',
            field=models.CharField(blank=True, choices=[('N', 'North'), ('S', 'South')], help_text='\n    If the location is in the northern hemisphere, and has a positive latitude,\n    then the latitude cardinality is North.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='knownlocation',
            name='longitude',
            field=models.FloatField(blank=True, help_text='Decimal longitude, e.g. 128.7490', null=True),
        ),
        migrations.AlterField(
            model_name='knownlocation',
            name='longitude_direction',
            field=models.CharField(blank=True, choices=[('E', 'East'), ('W', 'West')], help_text='\n    If the location is in the western hemisphere, and has a negative longitude,\n    then the longitude cardinality is East.', max_length=1, null=True),
        ),
        migrations.AlterField(
            model_name='knownlocation',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='knownperson',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='localization',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='location',
            name='authority',
            field=models.ForeignKey(blank=True, help_text='\n    Use this field to specify a known location (i.e. a location with an entry\n    in the GeoNames database).', null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.KnownLocation'),
        ),
        migrations.AlterField(
            model_name='location',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='partof',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='person',
            name='authority',
            field=models.ForeignKey(blank=True, help_text='\n    Use this field to specify a known person (i.e. a person with an entry in\n    the Conceptpower name authority).', null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.KnownPerson'),
        ),
        migrations.AlterField(
            model_name='person',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.CharField(choices=[('CM', 'Corporation Member'), ('TR', 'Trustee'), ('FEL', 'Friday Evening Lecturer')], default='CM', max_length=3),
        ),
        migrations.AlterField(
            model_name='position',
            name='validated',
            field=models.BooleanField(default=False, help_text='Indicates that a record has been examined for accuracy. This does not necessarily mean that the record has been disambiguated with respect to an authority accord.'),
        ),
    ]
