# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-04 00:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0020_historicalposition_position'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='role',
            field=models.CharField(choices=[(b'Corporation Member', b'Corporation Member'), (b'Trustee', b'Trustee'), (b'Friday Evening Lecturer', b'Friday Evening Lecturer')], max_length=255),
        ),
        migrations.AlterField(
            model_name='position',
            name='role',
            field=models.CharField(choices=[(b'Corporation Member', b'Corporation Member'), (b'Trustee', b'Trustee'), (b'Friday Evening Lecturer', b'Friday Evening Lecturer')], max_length=255),
        ),
    ]
