# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2018-02-19 19:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0020_auto_20180219_1854'),
    ]

    operations = [
        migrations.AddField(
            model_name='historicalinvestigator',
            name='institution',
            field=models.ForeignKey(blank=True, db_constraint=False, null=True, on_delete=django.db.models.deletion.DO_NOTHING, related_name='+', to='browser.Institution'),
        ),
        migrations.AddField(
            model_name='investigator',
            name='institution',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='browser.Institution'),
        ),
    ]
