# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-08 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0021_auto_20171104_0030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='start_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(blank=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_date',
            field=models.DateField(blank=True),
        ),
    ]
