# -*- coding: utf-8 -*-
# Generated by Django 1.11.1 on 2017-11-14 16:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('browser', '0022_auto_20171108_1836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='historicalposition',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='historicalposition',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='end_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='position',
            name='start_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
